<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../Workflow.Application/Workflow.Application.csproj" />
	<ProjectReference Include="../Workflow.Persistence/Workflow.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
	<Content Include="appsettings.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

</Project>
